name: Python Scripts Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run once every day at 00:00 UTC

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List repository contents
        run: ls -R

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r .github/requirements.txt

      - name: Run update_issue_count.py
        run: python update_issue_count.py

      - name: Run update_related_items_list.py
        run: python update_related_items_list.py

      - name: Run update_rr_oks_version.py
        run: python update_rr_oks_version.py
