name: Python Script action

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minutes

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List contents (for debugging)
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r ".github/requirements.txt"

      - name: Run Python script
        run: |
          python "update_rr_oks_version.py"
