name: Python Script action

on:
  schedule:
    - cron: '*/10 * * * *'  # This cron expression runs every 10 minutes

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust the Python version based on your needs

      - name: Install dependencies
        run: |
          pip install -r "Azure-automation/.github/requirements.txt"  # Correct path to requirements.txt

      - name: Run Python script
        run: |
          python "Azure-automation/update_rr_oks_version.py"  # Correct path to your Python script
